stages:
  data_preparation:
    cmd: python data_preparation.py -id data/raw -od data/prepared -p params.yaml
    deps:
      - data_preparation.py
      - data/raw
    outs:
      - data/prepared
    params:
      - data_preparation

# model construction:
#