stages:
  data_preparation:
    cmd: python data_preparation.py -id data/raw -od data/prepared
    deps:
      - data_preparation.py
      - data/raw
    outs:
      - data/prepared
    params:
      - data_preparation
  linear_regression:
    cmd: python liney_lineyich.py -id data/prepared -od data/models -mn ${linear_regression.model_name}
    deps:
      - liney_lineyich.py
      - data/prepared
    outs:
      - data/models/${linear_regression.model_name}.csv
      - data/models/${linear_regression.model_name}.joblib
    params:
      - linear_regression

  linear_regression_validation:
    cmd: python liney_lineyich_invalid.py -id data/prepared/ -im data/models/${linear_regression.model_name}.joblib -mn ${linear_regression.model_name}
    deps:
      - liney_lineyich_invalid.py
      - data/prepared/
      - data/models/${linear_regression.model_name}.joblib
    params:
      - linear_regression

  linear_regression_prod_version:
    cmd: python liney_lineyich_prod.py -id data/prepared/ -od data/models/ -mn ${linear_regression.model_name}
    deps:
      - liney_lineyich_prod.py
      - data/prepared
      - data/models/${linear_regression.model_name}.joblib
    outs:
      - data/models/${linear_regression.model_name}_prod.csv
      - data/models/${linear_regression.model_name}_prod.joblib
    params:
      - linear_regression
