stages:
  data_preparation:
    cmd: python data+preparation.py -id data/row -od data/prepared -p params.yaml
    deps:
      - data_preparation.py
      - data/raw
    outs:
      - data/prepared
    params:
      - data_preparation