data_preparation:
  train_test_ratio: 0.8
  train_val_ratio: 0.9
  random_state: 42
linear_regression:
  model_name: 'LinearRegression'
decision_tree:
  DecisionTree:
    max_depth: [ 3, 5, 8, 12]
    splitter: [ 'best', 'random']
    min_samples_split: [ 2, 4, 6, 8]
    min_samples_leaf: [ 1, 2, 4]
  RandomForest:
    n_estimators: [1, 3, 5, 10]
    max_depth: [ 3, 5, 8, 12]
    min_samples_split: [ 1, 2, 4, 8]
    min_samples_leaf: [ 1, 2, 4]
  ExtraTree:
    n_estimators: [ 1, 3, 5, 10 ]
    max_depth: [ 3, 5, 8, 12 ]
    min_samples_split: [ 1, 2, 4, 8 ]
    min_samples_leaf: [ 1, 2, 4]