stages:
  data_preparation:
    cmd: python data_preparation.py -id data/raw -od data/prepared
    deps:
      - data_preparation.py
      - data/raw
    outs:
      - data/prepared
    params:
      - data_preparation
  linear_regression:
    cmd: python linear_regression.py -id data/prepared -od data/models -mn ${linear_regression.model_name}
    deps:
      - linear_regression.py
      - data/prepared
    outs:
      - data/models/${linear_regression.model_name}.csv
      - data/models/${linear_regression.model_name}.joblib
    params:
      - linear_regression
  linear_regression_validation:
    cmd: python linear_regression_validation.py -id data/prepared/ -im data/models/ -mn ${linear_regression.model_name}
    deps:
      - linear_regression_validation.py
      - data/prepared/
      - data/models/
    params:
      - linear_regression
  linear_regression_prod_version:
    cmd: python linear_regression_full.py -id data/prepared/ -od data/models/ -mn ${linear_regression.model_name}
    deps:
      - linear_regression_full.py
      - data/prepared
      - data/models/${linear_regression.model_name}.joblib
    outs:
      - data/models/${linear_regression.model_name}_prod.csv
      - data/models/${linear_regression.model_name}_prod.joblib
    params:
      - linear_regression
  decision_tree:
    foreach: ${decision_tree}
    do:
      cmd: python decision_tree.py -id data/prepared -od data/models -bm data/models/${linear_regression.model_name}_prod.joblib -mn ${key} -p params.yaml
      deps:
        - decision_tree.py
        - data/prepared
        - data/models/${linear_regression.model_name}_prod.joblib
      outs:
        - data/models/${key}.joblib
      params:
        - decision_tree
  decision_tree_validation:
      foreach: ${decision_tree}
      do:
        cmd: python decision_tree_validation.py -id data/prepared/ -im data/models/ -bm data/models/${linear_regression.model_name}_prod.joblib -mn ${key}
        deps:
          - decision_tree_validation.py
          - data/prepared/
          - data/models/
          - data/models/${linear_regression.model_name}_prod.joblib
        params:
          - decision_tree
  decision_tree_prod_version:
      foreach: ${decision_tree}
      do:
        cmd: python decision_tree_full.py -id data/prepared/ -od data/models/ -mn ${key}
        deps:
          - decision_tree_full.py
          - data/prepared
          - data/models/${key}.joblib
        outs:
          - data/models/${key}_prod.joblib
        params:
          - decision_tree
  XGBoosting:
    cmd: python XGBoosting.py -id data/prepared -od data/models -mn ${XGBoosting.model_name}
    deps:
      - XGBoosting.py
      - data/prepared
    outs:
      - data/models/${XGBoosting.model_name}.joblib
    params:
      - XGBoosting
  XGBoosting_validation:
    cmd: python XGBoosting_validation.py -id data/prepared/ -im data/models/ -mn ${XGBoosting.model_name}
    deps:
      - XGBoosting_validation.py
      - data/prepared/
      - data/models/
    params:
      - XGBoosting
  XGBBoosting_prod_version:
    cmd: python XGBoosting_full.py -id data/prepared/ -od data/models/ -mn ${XGBoosting.model_name}
    deps:
      - XGBoosting_full.py
      - data/prepared
      - data/models/${XGBoosting.model_name}.joblib
    outs:
      - data/models/${XGBoosting.model_name}_prod.joblib
    params:
      - XGBoosting
  CatBoosting:
    cmd: python CatBoosting.py -id data/prepared -od data/models -mn ${CatBoosting.model_name} -p params.yaml
    deps:
      - CatBoosting.py
      - data/prepared
    outs:
      - data/models/${CatBoosting.model_name}.joblib
    params:
      - CatBoosting
  CatBoosting_validation:
    cmd: python CatBoosting_validation.py -id data/prepared/ -im data/models/ -mn ${CatBoosting.model_name}
    deps:
      - CatBoosting_validation.py
      - data/prepared/
      - data/models/
    params:
      - CatBoosting
  CatBoosting_prod_version:
    cmd: python CatBoosting_full.py -id data/prepared/ -od data/models/ -mn ${CatBoosting.model_name} -p params.yaml
    deps:
      - XGBoosting_full.py
      - data/prepared
      - data/models/${CatBoosting.model_name}.joblib
    outs:
      - data/models/${CatBoosting.model_name}_prod.joblib
    params:
      - CatBoosting
  NeuralNetwork:
    cmd: python NeuralNetwork.py -id data/prepared -od data/models -mn ${NeuralNetwork} -p params.yaml
    deps:
      - NeuralNetwork.py
      - data/prepared
    outs:
      - data/models/NeuralNetwork
    params:
      - NeuralNetwork
  NeuralNetwork_validation:
    cmd: python NeuralNetwork_validation.py -id data/prepared/ -im data/models/NeuralNetwork -bm data/models/${linear_regression.model_name}_prod.joblib
    deps:
      - NeuralNetwork_validation.py
      - data/prepared/
      - data/models/
    params:
      - NeuralNetwork
  NeuralNetwork_prod_version:
    cmd: python NeuralNetwork_full.py -id data/prepared/ -od data/models -bm data/models/${linear_regression.model_name}_prod.joblib
    deps:
      - NeuralNetwork_full.py
      - data/prepared
      - data/models/NeuralNetwork
    outs:
      - data/models/NeuralNetwork_prob