stages:
  data_preparation:
    cmd: python data_preparation_1.py -id data/raw/dataset1 -od data/prepared
    params:
    - data_preparation
    deps:
    - data/raw/dataset1
    - data_preparation_1.py
    outs:
    - data/prepared/