stages:
  data_preparation:
    cmd: python data_preparation_1.py -id data/raw/dataset1 -od data/prepared
    params:
    - data_preparation
    deps:
    - data/raw/dataset1
    - data_preparation_1.py
    outs:
    - data/prepared/
  linear_regression:
    cmd: python linear_regression.py -id data/prepared -od data/models -mn ${linear_regression.model_name}
    params:
    - linear_regression
    deps:
    - linear_regression.py
    - data/prepared
    outs:
    - data/models/${linear_regression.model_name}.csv
    - data/models/${linear_regression.model_name}.joblib