stages:
  data_preparation:
    cmd: python data_preparation_1.py -id data/raw/dataset1 -od data/prepared
    params:
    - data_preparation
    deps:
    - data/raw/dataset1
    - data_preparation_1.py
    outs:
    - data/prepared
  regression_train:
    cmd: python regression_train.py -id data/prepared -od data/models -mn ${regression.model_name}
    params:
    - regression
    deps:
    - regression_train.py
    - data/prepared
    outs:
    - data/models/${regression.model_name}.csv
    - data/models/${regression.model_name}.joblib
  regression_validation:
    cmd: python regression_validation.py -id data/prepared -im data/models
    params:
    - regression
    deps:
    - regression_validation.py
    - data/prepared
    - data/models/${regression.model_name}.joblib
  regression_test:
    cmd: python regression_test.py -id data/prepared -im data/models/${regression.model_name}.joblib -mn ${regression.model_name}
    params:
    - regression
    deps:
    - regression_test.py
    - data/prepared
    - data/models/${regression.model_name}.joblib
  regression_prod:
    cmd: python regression_full.py -id data/prepared -od data/models -mn ${regression.model_name}
    params:
    - regression
    deps:
    - regression_full.py
    - data/prepared
    - data/models/${regression.model_name}.joblib
    outs:
    - data/models/${regression.model_name}_prod.csv
    - data/models/${regression.model_name}_prod.joblib
  decision_tree:
    foreach: ${decision_tree}
    do:
      cmd: python decision_tree.py -id data/prepared -od data/models -bm data/models/${regression.model_name}_prod.joblib -mn ${key} -p params.yaml
      deps:
        - decision_tree.py
        - data/prepared
        - data/models/${regression.model_name}_prod.joblib
      outs:
        - data/models/${key}.joblib
      params:
        - decision_tree
  decision_tree_test:
    foreach: ${decision_tree}
    do:
      cmd: python decision_tree_test.py -id data/prepared/ -im data/models/${key}.joblib -bm data/models/${regression.model_name}_prod.joblib -mn ${key}
      deps:
        - decision_tree_test.py
        - data/prepared/
        - data/models/${key}.joblib
        - data/models/${regression.model_name}_prod.joblib
      params:
        - decision_tree
  decision_tree_prod:
    foreach: ${decision_tree}
    do:
      cmd: python decision_tree_full.py -id data/prepared/ -od data/models/ -mn ${key}
      deps:
        - decision_tree_full.py
        - data/prepared
        - data/models/${key}.joblib
      outs:
        - data/models/${key}_prod.joblib
      params:
        - decision_tree