stages:
  data_preparation:
    cmd: python data_preparation_1.py -id data/raw -od data/prepared
    params:
    - data_preparation
    deps:
    - data/raw/rawDataset1.csv
    - data_preparation_1.py
    outs:
    - data/prepared/