stages:
  data_preparation:
    cmd: python data_preparation_1.py -id data/raw/dataset1 -od data/prepared
    params:
    - data_preparation
    deps:
    - data/raw/dataset1
    - data_preparation_1.py
    outs:
    - data/prepared/
  regression_train:
    cmd: python regression_train.py -id data/prepared -od data/models -mn ${regression.model_name}
    params:
    - regression
    deps:
    - regression_train.py
    - data/prepared
    outs:
    - data/models/${regression.model_name}.csv
    - data/models/${regression.model_name}.joblib
  regression_validation:
    cmd:
    params:
    deps:
    outs:
  regression_test:
    cmd:
    params:
    deps:
    outs: