data_preparation:
  train_ratio: 0.7
  validation_test_ratio: 0.5
  random_state: 18
regression:
  model_name: 'Ridge'
  alpha_start_value: 1.0
  alpha_sweep_step: 1.0
  alpha_end_value: 10.0
  l1_ratio_start_value: 0.01
  l1_ratio_sweep_step: 0.01
  l1_ratio_end_value: 0.11
  alpha: 1.0
  l1_ratio: 0.01