data_preparation:
  train_ratio: 0.7
  validation_test_ratio: 0.5
  random_state: 18
regression:
  model_name: 'Ridge'
  alpha_start_value: 1.0
  alpha_sweep_step: 1.0
  alpha_end_value: 10.0
  l1_ratio_start_value: 0.01
  l1_ratio_sweep_step: 0.01
  l1_ratio_end_value: 0.11
  alpha: 1.0
  l1_ratio: 0.01
decision_tree:
  DecisionTree:
    max_depth: [ 2, 4, 6, 7 ]
    splitter: [ 'best', 'random' ]
    min_samples_split: [ 2, 3, 4 ]
    min_samples_leaf: [ 1, 2, 3, 4 ]
  RandomForest:
    n_estimators: [1, 2, 5, 10, 15]
    max_depth: [ 2, 4, 6, 7 ]
    min_samples_split: [ 2, 3, 4, 6, 7 ]
    min_samples_leaf: [ 1, 2, 3, 4 ]
  ExtraTree:
    n_estimators: [1, 2, 5, 10, 15]
    max_depth: [ 2, 4, 6, 7 ]
    min_samples_split: [ 2, 3, 4, 10, 15 ]
    min_samples_leaf: [ 1, 2, 3, 4, 18, 48 ]